/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ine;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 *
 * @author randy
 */
public class Estados extends javax.swing.JFrame {

    /**
     * Creates new form Estados
     */
    public Estados() {
        initComponents();
        cargarDatos();
    }

    public void cargarDatos() {
        DefaultTableModel dtm = (DefaultTableModel) jtEstados.getModel();
        dtm.setRowCount(0);
        Connection c = Conexion.getConnection();
        try {
            PreparedStatement ps = c.prepareStatement("SELECT * FROM Entidades \n" +
"UNION\n" +
"SELECT * FROM [192.168.0.232].[INE_NORTE].[dbo].[Entidades]\n" +
"UNION\n" +
"SELECT * FROM [192.168.0.108].[INE_CENTRO].[dbo].[Entidades]");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] Fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    Fila[i] = rs.getObject(i + 1);
                }
                dtm.addRow(Fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Estados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstados = new javax.swing.JTable();
        jbEliminar = new javax.swing.JButton();
        jbModidicar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIdEntidad = new javax.swing.JTextField();
        jtfNombreEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfClave = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Entidad", "Nombre", "Clave"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEstadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEstados);

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModidicar.setText("Actualizar");
        jbModidicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModidicarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Entidad");

        jLabel2.setText("Nombre");

        jLabel3.setText("Clave");

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfClave, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jtfNombreEstado)
                            .addComponent(jtfIdEntidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiar))
                            .addComponent(jbEliminar)
                            .addComponent(jbModidicar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 111, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfIdEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombreEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbGuardar)
                            .addComponent(jbLimpiar))
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jbModidicar)))
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try {
            int idEntidad = Integer.parseInt(jtfIdEntidad.getText());
            String nombreEstado = jtfNombreEstado.getText();
            String clave = jtfClave.getText();
            Connection c = Conexion.getConnection();
            java.sql.PreparedStatement ps = c.prepareStatement("INSERT INTO [127.0.0.1].[CITAS_INE].[dbo].[Entidades] VALUES (?,?,?)");
            ps.setInt(1, idEntidad);
            ps.setString(2, nombreEstado);
            ps.setString(3, clave);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado con Éxito");
            limpiar();
            cargarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGuardarActionPerformed

    public void limpiar() {
        jtfIdEntidad.setText("");
        jtfNombreEstado.setText("");
        jtfClave.setText("");
    }

    private void jbModidicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModidicarActionPerformed
        if (jtfIdEntidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ERROR:Debe seleccionar una entidad válida");
        } else {
            int idEntidad = Integer.parseInt(jtfIdEntidad.getText());
            String nombreEstado = jtfNombreEstado.getText();
            String clave = jtfClave.getText();
            Connection c = Conexion.getConnection();
            try {
                java.sql.PreparedStatement ps = c.prepareStatement("0");
                if (idEntidad<10){
                                  c.prepareStatement("UPDATE [127.0.0.1].[INE_SUR].[dbo].[Entidades] SET nombre = ? , clave= ? where id=?");  
                }
                if (idEntidad>10 && idEntidad<18){
                                  c.prepareStatement("UPDATE [192.168.0.108].[INE_CENTRO].[dbo].[Entidades] SET nombre = ? , clave= ? where id=?");  
                }
                if (idEntidad>18){
                                  c.prepareStatement("UPDATE [192.168.0.232].[INE_NORTE].[dbo].[Entidades] SET nombre = ? , clave= ? where id=?");  
                }
                ps.setInt(3, idEntidad);
                ps.setString(1, nombreEstado);
                ps.setString(2, clave);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro Actualizado con Éxito");
                limpiar();
                cargarDatos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_jbModidicarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtfIdEntidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ERROR:Debe seleccionar una entidad válida");
        } else {
            int idEntidad = Integer.parseInt(jtfIdEntidad.getText());
            String nombreEstado = jtfNombreEstado.getText();
            String clave = jtfClave.getText();
            Connection c = Conexion.getConnection();
            try {
                java.sql.PreparedStatement ps = c.prepareStatement("Delete from [127.0.0.1].[CITAS_INE].[dbo].[Entidades] where id=?");
                ps.setInt(1, idEntidad);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro Eliminado con Éxito");
                limpiar();
                cargarDatos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());

            }
        }

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstadosMouseClicked
        //JOptionPane.showMessageDialog(null, jtEstados.getValueAt(jtEstados.getSelectedRow(), 0));
        int id = Integer.parseInt(jtEstados.getValueAt(jtEstados.getSelectedRow(), 0) + "");
        try {
            Connection c = Conexion.getConnection();
            PreparedStatement ps = c.prepareStatement("select id,nombre,clave from [127.0.0.1].[CITAS_INE].[dbo].[Entidades] where id=?");
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jtfIdEntidad.setText(rs.getString("ID") + "");
                jtfNombreEstado.setText(rs.getString("Nombre"));
                jtfClave.setText(rs.getString("Clave"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Estados.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jtEstadosMouseClicked

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModidicar;
    private javax.swing.JTable jtEstados;
    private javax.swing.JTextField jtfClave;
    private javax.swing.JTextField jtfIdEntidad;
    private javax.swing.JTextField jtfNombreEstado;
    // End of variables declaration//GEN-END:variables
}
