/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ine;

import ine.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rc
 */
public class usuarios extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
        cargarEstados();
        limpiarDatos();
        cargarDatos();
    }

    private void limpiarDatos() {
        txtCurp.setText("");
        txtNombre.setText("");
        txtAPaterno.setText("");
        txtAMaterno.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        nacimiento.setDate(null);
        cbEntidadNac.setSelectedIndex(0);
        cbSexo.setSelectedIndex(0);
    }

    private String limpiar(String texto) {
        if (texto == null) {
            return "";
        }
        String n = java.text.Normalizer.normalize(texto, java.text.Normalizer.Form.NFD);
        return n.replaceAll("[^\\p{ASCII}]", "").replaceAll("[^A-Za-z]", "").toUpperCase();
    }

    private char primeraVocalInterna(String palabra) {
        for (int i = 1; i < palabra.length(); i++) {
            if ("AEIOU".indexOf(palabra.charAt(i)) >= 0) {
                return palabra.charAt(i);
            }
        }
        return 'X';
    }

    private boolean esPalabraInconveniente(String s) {
        String[] malas = {"BACA", "BAKA", "CACA", "CAGA", "COGE", "COJA", "CULO", "FALO",
            "JOTO", "LOCA", "LOCO", "MEAR", "MEON", "MOCO", "MULA", "NACO",
            "PEDA", "PEDO", "PENE", "PITO", "PUTA", "PUTO", "RATA", "SEXO",
            "SENO", "TETA", "VACA", "VAGA", "VAGO", "WUEY", "BUEY", "GUEY"};
        for (String m : malas) {
            if (m.equals(s)) {
                return true;
            }
        }
        return false;
    }

    private void cargarEstados() {
        try {
            Connection c = Conexion.getConnection();
            PreparedStatement ps = c.prepareStatement("select id,nombre,clave from Entidades");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbEntidadNac.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Estados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cargarDatos() {
        DefaultTableModel dtm = (DefaultTableModel) jtUsuarios.getModel();
        dtm.setRowCount(0);
        Connection c = Conexion.getConnection();
        try {
            PreparedStatement ps = c.prepareStatement("Select curp, nombre, aPaterno, aMaterno, fechaNac, entidadNac, sexo, telefono, email from [127.0.0.1].[CITAS_INE].[dbo].[Usuarios] order by curp");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] Fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    Fila[i] = rs.getObject(i + 1);
                }
                dtm.addRow(Fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Curp = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        aPaterno = new javax.swing.JLabel();
        aMaterno = new javax.swing.JLabel();
        fechaNac = new javax.swing.JLabel();
        entidadNac = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        txtAPaterno = new javax.swing.JTextField();
        cbEntidadNac = new javax.swing.JComboBox<>();
        cbSexo = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbCurp = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        nacimiento = new com.toedter.calendar.JDateChooser();
        jbEliminar = new javax.swing.JButton();
        jbModidicar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Curp.setText("*Curp");

        nombre.setText("*Nombre");

        aPaterno.setText("Apellido Paterno");

        aMaterno.setText("Apellido Materno");

        fechaNac.setText("Fecha de nacimiento");

        entidadNac.setText("Entidad Nacimiento");

        sexo.setText("Sexo");

        telefono.setText("Telefono");

        email.setText("Email");

        cbEntidadNac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion.." }));

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion..", "H", "M" }));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbCurp.setText("Generar Curp");
        jbCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCurpActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModidicar.setText("Actualizar");
        jbModidicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModidicarActionPerformed(evt);
            }
        });

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CURP", "Nombre", "Apellido Paterno", "Apellido Materno ", "Fecha de Nacimiento", "Entidad de Nacimiento", "Sexo", "Telefono", "eMail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre)
                                    .addComponent(aPaterno)
                                    .addComponent(Curp))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(aMaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCurp)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 499, Short.MAX_VALUE)
                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbModidicar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(entidadNac)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbEntidadNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(sexo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(telefono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar)
                    .addComponent(jbGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aPaterno)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMaterno)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModidicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Curp)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCurp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entidadNac)
                    .addComponent(cbEntidadNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexo)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCurpActionPerformed
        // TODO add your handling code here
        try {
            String ap = limpiar(txtAPaterno.getText().trim());
            String am = limpiar(txtAMaterno.getText().trim());
            String nom = limpiar(txtNombre.getText().trim());
            String sexo = cbSexo.getSelectedItem().toString().trim();

            if (ap.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Apellido paterno requerido.");
                return;
            }
            if (nom.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre requerido.");
                return;
            }
            if (nacimiento.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Fecha requerida.");
                return;
            }
            if (sexo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Elija su sexo.");
                return;
            }

            // --- Parte 1: 4 letras ---
            char c1 = ap.charAt(0);
            char c2 = primeraVocalInterna(ap);
            char c3 = am.isEmpty() ? 'X' : am.charAt(0);
            char c4 = nom.charAt(0);
            String parte1 = "" + c1 + c2 + c3 + c4;
            if (esPalabraInconveniente(parte1)) {
                parte1 = parte1.charAt(0) + "X" + parte1.substring(2);
            }

            // --- Parte 2: Fecha AAMMDD desde jDateChooser ---
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(nacimiento.getDate());
            String anio = String.valueOf(cal.get(java.util.Calendar.YEAR)).substring(2);
            String mes = String.format("%02d", cal.get(java.util.Calendar.MONTH) + 1);
            String dia = String.format("%02d", cal.get(java.util.Calendar.DAY_OF_MONTH));
            String parte2 = anio + mes + dia;

            // --- Parte 3: Sexo ---
            String curp = parte1 + parte2 + sexo;
            txtCurp.setText(curp);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar CURP: " + e.getMessage());
        }
    }//GEN-LAST:event_jbCurpActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String curp = txtCurp.getText().trim();
            String nombre = txtNombre.getText().trim();
            String ap = txtAPaterno.getText().trim();
            String am = txtAMaterno.getText().trim();
            String sexo = cbSexo.getSelectedItem().toString().trim();
            String telefono = txtTelefono.getText().trim();
            String email = txtEmail.getText().trim();

            if (curp.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Genera la CURP primero.");
                return;
            }
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre requerido.");
                return;
            }
            if (ap.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Apellido paterno requerido.");
                return;
            }
            if (am.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Apellido materno requerido.");
                return;
            }
            if (telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Teléfono requerido.");
                return;
            }
            if (nacimiento.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Fecha requerida.");
                return;
            }

            java.sql.Date fechaNac = new java.sql.Date(nacimiento.getDate().getTime());
            String nombreEntidad = cbEntidadNac.getSelectedItem().toString();

            Connection con = Conexion.getConnection();

            // Buscar ID de la entidad
            int entidadNac = 0;
            PreparedStatement psEnt = con.prepareStatement("SELECT id FROM Entidades WHERE nombre = ?");
            psEnt.setString(1, nombreEntidad);
            ResultSet rs = psEnt.executeQuery();
            if (rs.next()) {
                entidadNac = rs.getInt("id");
            } else {
                JOptionPane.showMessageDialog(this, "Entidad no encontrada.");
                return;
            }
            rs.close();
            psEnt.close();

            // Insertar usuario
            String sql = "INSERT INTO [127.0.0.1].[CITAS_INE].[dbo].[Usuarios] (curp, nombre, aPaterno, aMaterno, fechaNac, entidadNac, sexo, telefono, email) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, curp);
            ps.setString(2, nombre);
            ps.setString(3, ap);
            ps.setString(4, am);
            ps.setDate(5, fechaNac);
            ps.setInt(6, entidadNac);
            ps.setString(7, sexo);
            ps.setString(8, telefono);
            ps.setString(9, email.isEmpty() ? null : email);

            ps.executeUpdate();
            ps.close();
            con.close();

            JOptionPane.showMessageDialog(this, "Usuario guardado correctamente.");
            limpiarDatos();
            cargarDatos();
        } catch (Exception e) {
            if (e.getMessage() != null && e.getMessage().contains("PRIMARY KEY")) {
                JOptionPane.showMessageDialog(this, "Ya existe un usuario con esa CURP.");
            } else {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (txtCurp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ERROR:Escriba una CURP válida");
        } else {
            String curp = txtCurp.getText();
            Connection c = Conexion.getConnection();
            try {
                java.sql.PreparedStatement ps = c.prepareStatement("Delete from [127.0.0.1].[CITAS_INE].[dbo].[Usuarios] where curp like ?");
                ps.setString(1, curp);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Usuario Eliminado con Éxito");
                limpiarDatos();
                cargarDatos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModidicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModidicarActionPerformed
    if (txtCurp.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "ERROR:Debe introducir una CURP válida");
    } else {
        String curp = txtCurp.getText().trim();
        String nombre = txtNombre.getText().trim();
        String ap = txtAPaterno.getText().trim();
        String am = txtAMaterno.getText().trim();
        String sexo = cbSexo.getSelectedItem().toString().trim();
        String telefono = txtTelefono.getText().trim();
        String email = txtEmail.getText().trim();
        java.sql.Date fechaNac = new java.sql.Date(nacimiento.getDate().getTime());
        String nombreEntidad = cbEntidadNac.getSelectedItem().toString();

        try {
            Connection con = Conexion.getConnection();

            // Buscar ID de la entidad
            int entidadNac = 0;
            PreparedStatement psEnt = con.prepareStatement("SELECT id FROM [127.0.0.1].[CITAS_INE].[dbo].[Entidades] WHERE nombre = ?");
            psEnt.setString(1, nombreEntidad);
            ResultSet rs = psEnt.executeQuery();
            if (rs.next()) {
                entidadNac = rs.getInt("id");
            } else {
                JOptionPane.showMessageDialog(this, "Entidad no encontrada.");
                return;
            }
            rs.close();
            psEnt.close();

            // UPDATE correcto
            String sql = "UPDATE [127.0.0.1].[CITAS_INE].[dbo].[Usuarios] SET nombre = ?, aPaterno = ?, aMaterno = ?, fechaNac = ?, entidadNac = ?, sexo = ?, telefono = ?, email = ? WHERE curp = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nombre);
            ps.setString(2, ap);
            ps.setString(3, am);
            ps.setDate(4, fechaNac);
            ps.setInt(5, entidadNac);
            ps.setString(6, sexo);
            ps.setString(7, telefono);
            ps.setString(8, email.isEmpty() ? null : email);
            ps.setString(9, curp);

            ps.executeUpdate();
            ps.close();
            con.close();

            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            limpiarDatos();
            cargarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_jbModidicarActionPerformed

    private void jtUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuariosMouseClicked
  int fila = jtUsuarios.getSelectedRow();
    if (fila >= 0) {
        txtCurp.setText(jtUsuarios.getValueAt(fila, 0).toString());
        txtNombre.setText(jtUsuarios.getValueAt(fila, 1).toString());
        txtAPaterno.setText(jtUsuarios.getValueAt(fila, 2).toString());
        txtAMaterno.setText(jtUsuarios.getValueAt(fila, 3).toString());

        // Fecha de nacimiento
        try {
            String fechaStr = jtUsuarios.getValueAt(fila, 4).toString();
            java.sql.Date fechaSQL = java.sql.Date.valueOf(fechaStr);
            nacimiento.setDate(new java.util.Date(fechaSQL.getTime()));
        } catch (Exception e) {
            nacimiento.setDate(null);
        }

        // Entidad de nacimiento (columna 5 = idEntidad)
        try {
            int idEntidad = Integer.parseInt(jtUsuarios.getValueAt(fila, 5).toString());
            Connection c = Conexion.getConnection();
            PreparedStatement ps = c.prepareStatement("SELECT nombre FROM [127.0.0.1].[CITAS_INE].[dbo].[Entidades] WHERE id = ?");
            ps.setInt(1, idEntidad);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String nombreEntidad = rs.getString("nombre");
                cbEntidadNac.setSelectedItem(nombreEntidad);
            }
            rs.close();
            ps.close();
        } catch (Exception e) {
            cbEntidadNac.setSelectedIndex(0); // fallback
        }

        // Sexo
        cbSexo.setSelectedItem(jtUsuarios.getValueAt(fila, 6).toString());

        // Teléfono y email
        Object telObj = jtUsuarios.getValueAt(fila, 7);
        txtTelefono.setText(telObj != null ? telObj.toString() : "");

        Object emailObj = jtUsuarios.getValueAt(fila, 8);
        txtEmail.setText(emailObj != null ? emailObj.toString() : "");
    }


        // Entidad de nacimiento (columna 5)
        cbEntidadNac.setSelectedItem(jtUsuarios.getValueAt(fila, 5).toString());

        // Sexo
        cbSexo.setSelectedItem(jtUsuarios.getValueAt(fila, 6).toString());

        // Teléfono y email
        Object telObj = jtUsuarios.getValueAt(fila, 7);
        txtTelefono.setText(telObj != null ? telObj.toString() : "");

        Object emailObj = jtUsuarios.getValueAt(fila, 8);
        txtEmail.setText(emailObj != null ? emailObj.toString() : "");
    }//GEN-LAST:event_jtUsuariosMouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curp;
    private javax.swing.JLabel aMaterno;
    private javax.swing.JLabel aPaterno;
    private javax.swing.JComboBox<String> cbEntidadNac;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel entidadNac;
    private javax.swing.JLabel fechaNac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCurp;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModidicar;
    private javax.swing.JTable jtUsuarios;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
